Спринт 10.
Dw4yn33/java-filmorate pull request #4
Opened 2023-06-16 17:51 UTC by Dw4yn33

2023-06-16 19:37 UTC, Dw4yn33 commented
Все тесты пройдены.

2023-06-17 16:54 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично. 
После правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" и "Можно лучше"), присылай работу на завершение проверки.
Спасибо.

2023-06-17 16:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmComparator.java
> +        } else if (film1.getId() < film2.getId()) {
Можно лучше:

Как подсказывает IDE, строки с 14 по 19 можно заменить таким выражением (которое входит в стандартные утилиты языка, а значит, было много раз протестировано и снижает риск потенциальной ошибки в коде):
`else return Long.compare(film1.getId(), film2.getId());`

2023-06-17 16:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Component
Надо исправить:

В аннотации `@Service`, если посмотреть её код, уже содержится аннотация `@Component`, поэтому её добавление здесь избыточно.

Аналогичный комментарий справедлив для сервиса пользователей.

2023-06-17 16:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +@Component("InMemoryFilmStorage")
Можно лучше:

Если тип данных (класс) компонента не одинаков с другим подобным компонентом (т.е. если класс хранилища фильмов и класс хранилища пользователей, например, наследуются от разных интерфейсов), то можно не указывать в скобках к аннотации @Component имя для этого бина, т.к. по умолчанию оно будет равно названию класса. Это имя имеет смысл указывать для двух бинов, получаемых из одного класса (например, наследуемых от одного класса-предка).

2023-06-17 16:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmStorage filmStorage;
Можно лучше / Надо исправить:

Хотя в ТЗ нет однозначных указаний на то, что методы слоя репозиториев не должны попадать на слой контроллеров, исходя из таких практик построения современной бэкенд архитектуры ПО (с которыми ты познакомишься подробнее, скорее всего, уже на рабочих проектах), как Clean Code Architecture (https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) и построения трёх-звенной архитектуры ПО, следует избегать прямого обращения на слое контроллеров к слою репозиториев, чтобы обеспечить независимость этих слоёв друг от друга, что позволит при развитии проекта легко менять детали реализации каждого из слоёв, не трогая другой (что упрощает и ускоряет разработку, снижая также потенциальную сложность изменений и возможное внесение новых ошибок в код).

Поэтому здесь целесообразно добавить в слой сервисов недостающие у сервиса фильмов методы, которые уже будут обращаться к метода репозитория фильмов, чтобы на слое контроллеров использовать только методы сервиса фильмов, а весь код с вызовом методов репозитория фильмов из контроллера удалить.

Аналогичный комментарий справедлив для контроллера пользователей.

2023-06-17 16:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film getFilmByIndex(@PathVariable Long id) {
Отлично:

Отлично, что ты понимаешь разницу между @RequestParam и @PathVariable (кстати, см. небольшое напоминание об их отличиях, на англ. яз., здесь: https://stackoverflow.com/a/13718502)!

2023-06-17 16:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    public ErrorResponse handleValidation(final ValidationException e) {
Отлично:

Отлично, что помнишь о необходимости реализации (в соответствие с ТЗ) в т.ч. обработки исключений (ошибок) при валидации.

2023-06-17 19:01 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private FilmStorage filmStorage;
Исправлено

2023-06-17 19:01 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Component
Исправлено

2023-06-17 19:02 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean checkForFilmValidation(Film film) {
оставил public только ради тестов jUnit

2023-06-17 21:34 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    public boolean checkForFilmValidation(Film film) {
При такой структуре проекта (https://stackoverflow.com/a/3004775), обычной для многих maven и spring - based проектов, можно тестировать через junit также методы с модификаторами package-private, т.к. тестовый и тестируемый классы будут с т.з. JVM находиться в 1 пакете (хотя и в 2 разных директориях источниках (src), объяснение некоторых деталей - см., на англ. яз., например, тут, https://stackoverflow.com/a/3615031 , https://stackoverflow.com/questions/73178739/how-can-test-classes-in-maven-project-access-source-classes-from-main-folder ).

2023-06-17 21:36 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл важные комментарии, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-07-19 17:00 UTC, merged