Add database
Dw4yn33/java-filmorate pull request #6
Opened 2023-07-28 00:32 UTC by Dw4yn33

2023-07-28 21:41 UTC, z8q requested changes

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private LikeStorage likeStorage;
В строках 26-28 можно поставить final,  так как задаем один раз через конструктор

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +    public void add(Film film) {
По ТЗ предполагались только
GET /genres 
GET /genres/{id}

Может быть можно оставить, стоит посоветоваться с наставником

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
При отправке POST http://localhost:8080/films
```JSON
{
	"name": "Die Hard",
	"description": "Action movie with Br-s Wil-s",
	"releaseDate": "1988-07-22",
	"rating": 100,
	"duration": 1,
	"mpa": {
		"id": 1,
		"name":"NC-17",
		"description": "17+"
	},
	"genres": [
		{
			"name": "action"
		},
		{
			"id": 2,
			"name": "drama"
		},
		{
			"id": 3,
			"name": "comedy"
		}
	]
}
```

В первом жанре пропущен id.

Получаю ошибку:
```JSON
{
	"error": "Ошибка валидации",
	"description": "Передан пустой аргумент!"
}
```

Но фильм при этом сохраняется

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
Допускается сохранение дубликатов фильмов с одинаковыми name, description, releaseDate, duration

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public User create(User user) {
Допускается сохранение дубликатов пользователей

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public User create(User user) {
Допускается сохранение почты в таком виде `"email": "@@bob"`

Если для валидации использовать аннотацию `@Email` над полем в User, то проверка будет корректной.
Только при использовании валидационных аннотаций, в методе контроллера рядом с аргументом User user нужно еще ставить аннотацию `@Valid`, чтобы проверка заработала

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (user.getEmail().isEmpty()) {
Тут для полей нужна проверка на null,
POST http://localhost:8080/users
с body:
```JSON
{
	"login": "bobLogin",
	"name": "bob",
	"birthday": "2011-11-11"
}
```
или
```JSON
{
	"email": "bob@yandex.ru",
	"name": "bob",
	"birthday": "2011-11-11"
}
```

Тут будем падать с NullPointerException

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (user.getEmail().isEmpty()) {
При проверке полей у фильмов тоже такое возникает

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendStorage.java
> +    public void addFriend(Long userId, Long friendId) {
Повторные запросы на добавление в друзья, создают дубли записей в базе

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendStorage.java
> +    public void addFriend(Long userId, Long friendId) {
По статусу может не очень существенно,
но если я делаю
PUT http://localhost:8080/users/1/friends/2
и потом
PUT http://localhost:8080/users/2/friends/1
то поле статус для обеих записей все равно остается false

2023-07-28 21:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeStorage.java
> +    public void addLike(Long filmId, Long userId) {
Если дважды вызвать PUT http://localhost:8080/films/1/like/1
На второй раз получаем ошибку:
```JSON
{
	"error": "Произошла непредвиденная ошибка",
	"description": "PreparedStatementCallback; SQL [INSERT INTO film_likes (film_id, user_id) VALUES (?, ?)]; Unique index or primary key violation: \"PUBLIC.PRIMARY_KEY_7A ON PUBLIC.FILM_LIKES(FILM_ID, USER_ID) VALUES ( /* key:1 */ CAST(1 AS BIGINT), CAST(1 AS BIGINT))\"; SQL statement:\nINSERT INTO film_likes (film_id, user_id) VALUES (?, ?) [23505-214]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PUBLIC.PRIMARY_KEY_7A ON PUBLIC.FILM_LIKES(FILM_ID, USER_ID) VALUES ( /* key:1 */ CAST(1 AS BIGINT), CAST(1 AS BIGINT))\"; SQL statement:\nINSERT INTO film_likes (film_id, user_id) VALUES (?, ?) [23505-214]"
}
```

Внутренний sql-запрос выводить в ответе не очень хорошо, стоит заменить на текст с описанием ошибки

2023-07-28 22:02 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private LikeStorage likeStorage;
Сделано

2023-07-28 22:03 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreStorage.java
> +    public void add(Film film) {
Так только эти запросы и имеются в GenreController, не понимаю зачем нужно что-либо убирать

2023-07-28 23:26 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        if (user.getEmail().isEmpty()) {
сделано

2023-07-29 00:04 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public User create(User user) {
Исправлено

2023-07-29 00:51 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public Film create(Film film) {
Исправлено

2023-07-29 01:29 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/like/LikeStorage.java
> +    public void addLike(Long filmId, Long userId) {
Хотел добавить обработку этого исключения, но не смог и решил сделать костыль при обработке throwable.

2023-07-29 13:48 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/friend/FriendStorage.java
> +    public void addFriend(Long userId, Long friendId) {
Исправлено

2023-07-30 06:39 UTC, z8q requested changes

2023-07-30 06:39 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        if (e.getMessage().contains("org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException")) {
можно попробовать доставать .getCause, в зависимости от этого возвращать код и текст
Проверять getCause на instanceOf SomeExceptionClass.class

2023-07-30 06:39 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
if-ы допустимы, но в них можно запутаться
Как вариант, можно попробовать закомментировать этот блок.
В модели Genre над полем id поставить @NotNull(message = "id can't be null")
В модели Film поставить private Set<@Valid Genre> genres;

Но ошибка тогда будет проходить как Throwable,  в ErrorHandler написал, как можно обработать

2023-07-30 06:39 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        if (e.getMessage().contains("org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException")) {
тут в пункте 4 есть пример
https://www.baeldung.com/exception-handling-for-rest-with-spring
в котором можно определенный статус присваивать для ResponseEntity

2023-07-30 11:56 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        if (e.getMessage().contains("org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException")) {
Я нашел исключение, которое нужно обрабатывать для этого случая, это было DuplicateKeyException, нашел через getclass.

2023-07-30 12:08 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
Я оставлю if'ы, ибо с ними у меня готовое исключение, которое описывает ошибку. Я попробовал так, как вы сказали, но в таком случае у меня в e.getMessage() вылезает логика приложения, что вроде как нежелательно.

2023-07-30 12:19 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            if (!film.getGenres().isEmpty()) {
Если больше критичных ошибок нет, то пожалуйста, примите проект, у меня остался последний день для сдачи. Я исправил все ошибки, которые вы нашли и учел все замечания.

2023-07-30 12:20 UTC, Dw4yn33 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +        if (e.getMessage().contains("org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException")) {
Для случая с проставлением второго и далее лайков я имею ввиду.

2023-07-30 18:24 UTC, z8q approved these changes

2023-08-31 21:57 UTC, merged